# Generated by Django 4.2.8 on 2023-12-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_registration_password_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(default=888, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account_type',
            field=models.ForeignKey(choices=[('Saving Account', 'Saving Accoont'), ('Current Account', 'Current Account'), ('other', 'Other')], on_delete=django.db.models.deletion.CASCADE, to='banking_app.accounttype'),
        ),
    ]
