# Generated by Django 4.2.8 on 2023-12-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_registration_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='materials_provided',
            field=models.ManyToManyField(to='banking_app.material'),
        ),
    ]
